apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zabbix

resources:
  - namespace.yml
  - mysql-service.yml
  - mysql-statefulset.yml
  - zabbix-server-services.yml
  - zabbix-server-statefulset.yml
  - zabbix-web-service.yml
  - zabbix-web-deployment.yml
  - zabbix-web-ingress.yml