apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zabbix

resources:
  - mysql-service.yml
  - mysql-statefulset.yml
  - zabbix-server-services.yml
  - zabbix-server-statefulset.yml
  - zabbix-web-service.yml
  - zabbix-web-deployment.yml
  - zabbix-web-ingress.yml

secretGenerator:
  - name: zabbix-db-secret
    literals:
      - mysql-user=zabbix
      - mysql-password=Kosher-Everyone-Only1-Overvalue-Zodiac-Carving
      - mysql-root-password=changeme
      - mysql-database=zabbix
    options:
      disableNameSuffixHash: true