# https://github.com/grafana/loki/blob/main/production/helm/loki/distributed-values.yaml
# for chart: https://github.com/grafana/loki/tree/main/production/helm/loki

nodePools:
  controlPlane: &controlPlaneSelector
    node-role.kubernetes.io/control-plane: "true"
  logsIngest: &logsIngestSelector
    logs: "ingest"
  metricsHot: &metricsHotSelector
    metrics: "hot"
  tracesHot: &tracesHotSelector
    traces: "hot"
  queryCpu: &queryCpuSelector
    query: "cpu"
  general: &generalSelector
    general: "true"
  tierMinio: &minioSelector
    tier: "minio"

# Loki runtime config
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
          
  auth_enabled: false

  # Pattern ingester gives HTTP error 500?
  pattern_ingester:
    enabled: false
  
  # Configure limits for stability
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16
    max_global_streams_per_user: 5000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 168h # 7 days retention
    allow_structured_metadata: true
    volume_enabled: true

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      accessKeyId: minio
      secretAccessKey: minio123
      s3ForcePathStyle: true
      insecure: true
      http_config: {}

  ingester:
    chunk_encoding: snappy

  querier:
    max_concurrent: 2

# Helm deployment mode
deploymentMode: Distributed

# Component deployment configurations
ingester:
  zoneAwareReplication:
    enabled: false
  nodeSelector: *logsIngestSelector
  replicas: 3
  maxUnavailable: 1
  resources:
    requests:
      cpu: "1500m"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistence:
    enabled: true
    inMemory: false
    claims:
      - name: data
        size: 500Gi
  storageClass: standard

querier:
  replicas: 2
  maxUnavailable: 1
  nodeSelector: *queryCpuSelector
  resources:
    requests:
      cpu: "500m"
      memory: "768Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

queryFrontend:
  replicas: 2
  maxUnavailable: 1
  nodeSelector: *queryCpuSelector
  resources:
    requests:
      cpu: "800m"
      memory: "1.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

queryScheduler:
  replicas: 2
  nodeSelector: *logsIngestSelector
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

distributor:
  replicas: 2
  maxUnavailable: 2
  nodeSelector: *logsIngestSelector
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

compactor:
  replicas: 2
  nodeSelector: *logsIngestSelector
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

indexGateway:
  replicas: 2
  maxUnavailable: 1
  nodeSelector: *logsIngestSelector
  resources:
    requests:
      cpu: "500m"
      memory: "1.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Experimental bloom components
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

# Disable legacy deployment modes (this is for monolithic deployment)
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
singleBinary:
  replicas: 0

# Loki Gateway service
gateway:
  nodeSelector: *logsIngestSelector
  service:
    type: LoadBalancer

resultsCache:
  nodeSelector: *queryCpuSelector
  
chunksCache:
  nodeSelector: *queryCpuSelector

canary:
  enabled: false