image:
  registry: docker.io
  repository: grafana/grafana
  tag: "latest"
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

persistence:
  enabled: false

grafana.ini:
  server:
    root_url: "https://grafana.greypixel.nl"
  auth:
    disable_login_form: true
    oauth_auto_login: true
  auth.generic_oauth:
    enabled: true
    name: "SSO"
    client_id: $__file{/etc/grafana/oidc/client_id}
    client_secret: $__file{/etc/grafana/oidc/client_secret}
    scopes: "openid profile email groups"
    auth_url: https://auth.greypixel.nl/authorize
    token_url: https://auth.greypixel.nl/oauth/token
    api_url: https://auth.greypixel.nl/userinfo
    login_attribute_path: email
    name_attribute_path: name
    email_attribute_path: email
    role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
  tracing.opentelemetry.otlp:
    address: tempo-distributor.tempo.svc.cluster.local:4317
    insecure: true

extraSecretMounts:
  - name: oidc-secrets
    secretName: grafana-oidc-secrets
    mountPath: /etc/grafana/oidc
    readOnly: true

adminUser: Admin
adminPassword: a3vnwwEs

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki (smoke)
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'smoke'
      - name: Loki (fire)
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'fire'
      - name: Loki (spark)
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'spark'
      - name: Mimir (smoke)
        type: prometheus
        access: proxy
        url: http://mimir-nginx.mimir.svc:80/prometheus
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'smoke'
      - name: Mimir (fire)
        type: prometheus
        access: proxy
        url: http://mimir-nginx.mimir.svc:80/prometheus
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'fire'
      - name: Mimir (spark)
        type: prometheus
        access: proxy
        url: http://mimir-nginx.mimir.svc:80/prometheus
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'spark'
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        url: http://pyroscope-querier.pyroscope.svc.cluster.local.:4040/

env:
  GF_INSTALL_PLUGINS: grafana-pyroscope-app
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_DIAGNOSTICS_PROFILING_ENABLED: "true"
  GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
  GF_DIAGNOSTICS_PROFILING_PORT: 9094
  GF_DATABASE_TYPE: mysql
  GF_DATABASE_HOST: mysql-grafana.mysql-grafana.svc.cluster.local:3306
  GF_DATABASE_NAME: grafana
  GF_DATABASE_USER: grafana
  GF_DATABASE_PASSWORD: some-password-string
  GF_DATABASE_SSL_MODE: disable

podAnnotations:
  profiles.grafana.com/cpu.scrape: "true"
  profiles.grafana.com/cpu.port: "9094"
  profiles.grafana.com/memory.scrape: "true"
  profiles.grafana.com/memory.port: "9094"
  profiles.grafana.com/goroutine.scrape: "true"
  profiles.grafana.com/goroutine.port: "9094"
