cluster:
  name: kubernetes

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
  - name: localPrometheus
    type: prometheus
    url: http://mimir-nginx.mimir.svc:80/api/v1/push
  - name: tempo
    type: otlp
    protocol: http
    url: tempo-distributor.tempo.svc.cluster.local:4317
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
      processors:
        tailSampling:
          enabled: false

clusterEvents:
  enabled: true
  collector: alloy-logs

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep:
    - app_kubernetes_io_name
    - container
    - instance
    - job
    - level
    - namespace
    - service_name
    - service_namespace
    - deployment_environment
    - deployment_environment_name
  structuredMetadata:
    pod: pod

alloy-singleton:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true
  alloy:
    stabilityLevel: public-preview
    mounts:
      varlog: false
      dockercontainers: false
    clustering:
      enabled: true

clusterMetrics:
  enabled: true

alloy-receiver:
  enabled: false

applicationObservability:
  enabled: false
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

annotationAutodiscovery:
  enabled: false

alloy-profiles:
  enabled: false

extraConfig: |