image:
  registry: docker.io          # or your private registry
  repository: bitnami/minio    # default repo for the Bitnami chart
  tag: "latest"                # <— grab the `:latest` image
  pullPolicy: Always  

## Use the existing Secret for root creds
auth:
  existingSecret: minio-creds

## Expose only inside the cluster
service:
  type: ClusterIP
  ports:
    api:     9000
    console: 9001

## Distributed mode example
mode: distributed
replicas: 4

persistence:
  size: 100Gi
  storageClass: nfs-csi-retain

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1024Mi"

nodeSelector:
  tier: minio