cluster:
  name: kubernetes

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
    tenantId: spark # Set to Id of the tenant in Loki
  - name: localPrometheus
    type: prometheus
    url: http://mimir-nginx.mimir.svc:80/api/v1/push
    tenantId: spark # Set to Id of the tenant in Mimir
  - name: tempo
    type: otlp
    protocol: http        # http -> 4318, grpc -> 4317
    url: http://tempo-distributor.tempo.svc.cluster.local:4318
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true

integrations:
  collector: alloy-singleton
  # attach available node labels to all integration metrics collection
  nodeLabels:
    nodepool: true
    region: true
    availability_zone: true
    node_role: true
    os: true
    architecture: true
    instance_type: true

  alloy:
    instances:
      # monitor the collector gathering and sending meta-monitoring metrics/logs to the meta-monitoring cluster
      - name: alloy
        namespaces:
          - k8s-monitoring
        labelSelectors:
          app.kubernetes.io/name: alloy-singleton

      # monitor the collectors gathering and sending metrics/logs to the local cluster
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name: [alloy-singleton, alloy-metrics, alloy-logs, alloy-profiles, alloy-receiver]
        namespaces:
          - collectors

  grafana:
    instances:
      - name: grafana
        namespaces:
          - grafana
        labelSelectors:
          app.kubernetes.io/name: grafana

  loki:
    instances:
      - name: loki
        namespaces:
          - loki
        labelSelectors:
          app.kubernetes.io/name: loki
        logs:
          tuning:
            # extract logfmt fields and set them as structured metadata
            structuredMetadata:
              caller:
              tenant:
              org_id:
              user:
  mimir:
    instances:
      - name: mimir
        namespaces:
          - mimir
        labelSelectors:
          app.kubernetes.io/name: mimir
        logs:
          tuning:
            # extract logfmt fields and set them as structured metadata
            structuredMetadata:
              caller:
              tenant:
              org_id:
              user:

clusterEvents:
  enabled: true
  collector: alloy-logs

nodeLogs:
  enabled: true
  journal:
    units:
      - kubelet.service
      - containerd.service

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep:
    - app_kubernetes_io_name
    - container
    - instance
    - job
    - level
    - namespace
    - service_name
    - service_namespace
    - deployment_environment
    - deployment_environment_name
  structuredMetadata:
    pod: pod

alloy-singleton:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true
  alloy:
    clustering:
      enabled: true

# https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-cluster-metrics
clusterMetrics:
  enabled: true
  apiServer:
    enabled: true
  cadvisor: # default is true, here for clarity
    enabled: true
  controlPlane: # This includes api-server, kube-scheduler, kube-controller-manager, and KubeDNS.
    enabled: true


## Grafana Public Alloy: Start
# https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/helm-chart-config/helm-chart/collector-reference/
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318

alloy-receiver:
  enabled: true
  alloy:
    service:
    type: LoadBalancer
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
## Grafana PublicAlloy: End

annotationAutodiscovery:
  enabled: false

alloy-profiles:
  enabled: false