nodePools:
  controlPlane: &controlPlaneSelector
    node-role.kubernetes.io/control-plane: "true"
  logsIngest: &logsIngestSelector
    logs: "ingest"
  metricsHot: &metricsHotSelector
    metrics: "hot"
  tracesHot: &tracesHotSelector
    traces: "hot"
  queryCpu: &queryCpuSelector
    query: "cpu"
  general: &generalSelector
    general: "true"
  tierMinio: &minioSelector
    tier: "minio"

image:
  registry: docker.io
  repository: grafana/grafana
  tag: "latest"
  pullPolicy: IfNotPresent
replicas: 2
nodeSelector: *generalSelector
resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "2"
    memory: "8Gi"
persistence:
  enabled: true
  volumeName: ""
  accessModes:
    - ReadWriteMany
  size: 10Gi
  storageClass: "standard"
grafana.ini:
  server:
    root_url: "https://grafana.local"
  auth:
    disable_login_form: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-nginx.mimir.svc:80/prometheus
        #jsonData:
        #  httpHeaderName1: X-Scope-OrgID
        #secureJsonData:
        #  httpHeaderValue1: "1"
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        url: http://pyroscope-querier.pyroscope.svc.cluster.local.:4040/

env:
  GF_INSTALL_PLUGINS: grafana-pyroscope-app
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_DIAGNOSTICS_PROFILING_ENABLED: "true"
  GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
  GF_DIAGNOSTICS_PROFILING_PORT: 9094

podAnnotations:
  profiles.grafana.com/cpu.scrape: "true"
  profiles.grafana.com/cpu.port: "9094"
  profiles.grafana.com/memory.scrape: "true"
  profiles.grafana.com/memory.port: "9094"
  profiles.grafana.com/goroutine.scrape: "true"
  profiles.grafana.com/goroutine.port: "9094"