kubeProxyReplacement: true
k8sServiceHost: 192.168.50.10
k8sServicePort: 6443
envoy:
  enabled: true
  podAnnotations:
    k8s.grafana.com/scrape: "false"
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
gatewayAPI:
  enabled: true
gatewayController:
  enabled: true
l2announcements:
  enabled: true
  leaseDuration: 10
  leaseRenewDeadline: 5s
  leaseRetryPeriod: 1s
k8sClientRateLimit:
  qps: 20
  burst: 50
prometheus:
  enabled: true
ipam:
  mode: kubernetes
image:
  pullPolicy: IfNotPresent
podAnnotations:
  k8s.grafana.com/scrape: "true"
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - hubble.local