---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    ingress.cilium.io/loadbalancer-mode: "shared"
    ingress.cilium.io/proxy-read-timeout: "3600"
    ingress.cilium.io/proxy-send-timeout: "3600"
    ingress.cilium.io/websocket-services: "n8n"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: cilium
  tls:
    - hosts:
      - n8n.greypixel.nl
  rules:
    - host: n8n.greypixel.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678