apiVersion: v1
kind: Namespace
metadata:
  name: alloy-external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy-external
data:
  alloy.hcl: |
    otelcol.receiver.otlp "receiver" {
      http {}
      grpc {}

      output {
        logs    = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        logs    = [otelcol.exporter.otlphttp.loki.input]
      }
    }

    otelcol.exporter.otlphttp "loki" {
      client {
        endpoint = "http://loki-distributor.loki.svc.cluster.local:3100/otlp"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-deployment
  namespace: alloy-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      nodeSelector:
        logs: ingest
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/alloy.hcl"
          ports:
            - name: grpc-otlp
              containerPort: 4317
            - name: http2-otlp
              containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
          # optional probes
          livenessProbe:
            tcpSocket: { port: 4317 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: alloy-config
            items:
              - key: alloy.hcl
                path: alloy.hcl
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-service
  namespace: alloy-external
spec:
  type: LoadBalancer
  selector:
    app: alloy
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: grpc-otlp
    - name: http2-otlp
      port: 4318
      targetPort: http2-otlp
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: alloy-gateway
  namespace: alloy-namespace
spec:
  gatewayClassName: cilium
  listeners:
    - name: alloy-listener
      protocol: HTTP
      port: 4317
      allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy-route
  namespace: alloy-namespace
spec:
  parentRefs:
  - name: alloy-gateway
    sectionName: alloy-listener
  hostnames:
  - otlp.local
  rules:
  - backendRefs:
    - name: alloy-service
      port: 4317