---
apiVersion: v1
kind: Namespace
metadata:
  name: alloy-external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy-external
data:
  alloy.hcl: |
    otelcol.receiver.otlp "receiver" {
      http {}
      grpc {}

      output {
        logs    = [otelcol.processor.batch.default.input]
        metrics = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        logs    = [otelcol.exporter.otlphttp.loki.input]
        metrics = [otelcol.exporter.otlphttp.mimir.input]
      }
    }

    otelcol.exporter.otlphttp "loki" {
      client {
        endpoint = "http://loki-distributor.loki.svc.cluster.local:3100/otlp"
      }
    }

    otelcol.exporter.otlphttp "mimir" {
      client {
        endpoint = "http://mimir-distributor.mimir.svc.cluster.local:8080/otlp"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-deployment
  namespace: alloy-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      nodeSelector:
        logs: ingest
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/alloy.hcl"
          ports:
            - name: http2-otlp
              containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
          livenessProbe:
            tcpSocket: { port: 4318 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: alloy-config
            items:
              - key: alloy.hcl
                path: alloy.hcl
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-service
  namespace: alloy-external
spec:
  type: ClusterIP
  selector:
    app: alloy
  ports:
    - name: http2-otlp
      port: 4318
      targetPort: http2-otlp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy-external-ingress
  namespace: alloy-external
spec:
  ingressClassName: nginx
  rules:
    - host: otlp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alloy-service
                port:
                  number: 4318