---
apiVersion: v1
kind: Namespace
metadata:
  name: alloy-external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy-external
data:
  alloy.hcl: |
    otelcol.receiver.otlp "receiver" {
      http {}
      grpc {}

      output {
        metrics = [otelcol.processor.batch.default.input]
        logs    = [otelcol.processor.batch.default.input]
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      send_batch_size     = 1024
      send_batch_max_size = 2048
      timeout             = "5s"

      output {
        metrics = [
          otelcol.exporter.prometheus.local.input,
        ]
        logs = [
          otelcol.exporter.loki.loki.input,
        ]
        traces = [
          otelcol.exporter.otlp.tempo.input,
        ]
      }
    }

    otelcol.exporter.otlphttp "loki_incluster" {
      endpoint = "http://loki-distributor.loki.svc.cluster.local:3100/otlp"
    }

    otelcol.exporter.otlphttp "mimir_incluster" {
      endpoint = "http://mimir-distributor.mimir.svc.cluster.local:8080/otlp"
    }

    otelcol.exporter.otlphttp "tempo_incluster" {
      endpoint = "http://tempo-distributor.tempo.svc.cluster.local:4318"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-deployment
  namespace: alloy-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/alloy.hcl"
          ports:
            - name: http2-otlp
              containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
          livenessProbe:
            tcpSocket: { port: 4318 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: alloy-config
            items:
              - key: alloy.hcl
                path: alloy.hcl
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-service
  namespace: alloy-external
spec:
  type: LoadBalancer
  selector:
    app: alloy
  ports:
    - name: http2-otlp
      port: 4318
      targetPort: http2-otlp