apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DB_SERVER_HOST
              value: zabbix-mysql.zabbix-dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: DB_SERVER_HOST
              value: zabbix-mysql.zabbix-dev.svc.cluster.local