apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
  namespace: zabbix-dev
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix-dev
spec:
  replicas: 2
