apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
