---
## Namespace is deployed with Keycloak Operator
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: keycloak
#  annotations:
#    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: v1
kind: Secret
metadata:
  name: kc-db
  namespace: keycloak
type: Opaque
stringData:
  username: Dumping7041
  password: Chirpy-Overplant-Uneasily-Stout-Trace-Splatter-Gladly-Sensitize3
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
stringData:
  username: Armory1825
  password: Decipher-Bladder-Thus9-Unclip-Anime-Deepen-Wobbling-Overblown
---
apiVersion: v1
kind: Service
metadata:
  name: kc-postgres
  namespace: keycloak
  labels:
    app: kc-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: kc-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kc-postgres
  namespace: keycloak
spec:
  serviceName: kc-postgres
  replicas: 1
  selector:
    matchLabels:
      app: kc-postgres
  template:
    metadata:
      labels:
        app: kc-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kc-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-db
                  key: password
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            exec:
              command: ["bash","-lc","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["bash","-lc","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: kc
  namespace: keycloak
spec:
  instances: 1
  http:
    httpEnabled: true
  hostname:
    hostname: https://auth.greypixel.nl
    strict: true
  additionalOptions:
    - name: proxy-headers
      value: xforwarded
  admin:
    usernameSecret:
      name: keycloak-admin-credentials
      key: username
    passwordSecret:
      name: keycloak-admin-credentials
      key: password
  db:
    vendor: postgres
    host: kc-postgres.keycloak.svc
    port: 5432
    database: keycloak
    usernameSecret:
      name: kc-db
      key: username
    passwordSecret:
      name: kc-db
      key: password
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      namespace: keycloak
      name: kc-ingress
      managedFieldsManagers:
        - keycloakcontroller
