apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DB_SERVER_HOST
              value: mysql.zabbix-prod.svc.cluster.local