apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
spec:
  replicas: 2   # Min 2, because of HA config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 2
