---
apiVersion: v1
kind: Namespace
metadata:
  name: telegraf-external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: telegraf-external
data:
  telegraf.conf: |
    [[inputs.exec]]
      interval = "60s"
      commands=["uptime"]
      timeout = "40s"
      data_format = "csv"
      csv_skip_rows = 1
      csv_column_names=["", "", "status", "dest", "hop", "ip", "loss", "snt", "", "", "avg", "best", "worst", "stdev"]
      name_override = "mtr"
      csv_tag_columns = ["dest", "hop", "ip"]

    [[outputs.file]]
      files = ["stdout"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: telegraf-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-external
  template:
    metadata:
      labels:
        app: telegraf-external
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.36.2-alpine
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: 8125-udp
              protocol: UDP
              containerPort: 8125
            - name: 8092-udp
              protocol: UDP
              containerPort: 8092
            - name: 8094-tcp
              protocol: TCP
              containerPort: 8094
            - name: 1883-tcp
              protocol: TCP
              containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
              readOnly: true
          livenessProbe:
            tcpSocket: { port: 8094 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: telegraf-config
            items:
              - key: telegraf.conf
                path: telegraf.conf
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  namespace: telegraf-external
spec:
  type: LoadBalancer
  selector:
    app: telegraf-external
  ports:
    - name: 8125-udp
      port: 8125
      targetPort: 8125
    - name: 8092-udp
      port: 8092
      targetPort: 8092
    - name: 8094-tcp
      port: 8094
      targetPort: 8094
    - name: 1883-tcp
      port: 1883
      targetPort: 1883