apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: grafana
  annotations:
    # Use HTTP/1.1 so that WebSocket Upgrade headers are respected
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"

    # Prevent idle WebSocket connections from being closed prematurely
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    
    # (Optional) If you have a lot of concurrent connections, you can tweak buffers:
    # nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    # nginx.ingress.kubernetes.io/proxy-buffers: "4 8k"
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80